version: "3"

volumes:
  mysql-data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=divenn
      - MYSQL_DBNAME=divenn

  mysql:
    image: "mysql:8"
    # ports:
    #   - 7033:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=divenn

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
